server:
  port: 9695
spring:
  datasource:
    url: jdbc:h2:mem:grocer
    driver-class-name: org.h2.Driver
    username: user
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
